namespace Routing.Domain.Enums
{
    public enum RoadClassType
    {
        OTHER, MOTORWAY, TRUNK, PRIMARY, SECONDARY, TERTIARY, RESIDENTIAL, UNCLASSIFIED,
        SERVICE, ROAD, TRACK, BRIDLEWAY, STEPS, CYCLEWAY, PATH, LIVING_STREET, FOOTWAY,
        PEDESTRIAN, PLATFORM, CORRIDOR, CONSTRUCTION, BUSWAY
    }
}
