services:
  api:
    build:
      context: ..
      dockerfile: server/Offroad.Api/Dockerfile
    container_name: offroad-api
    ports:
      - "5000:8080"
    environment:
      ASPNETCORE_ENVIRONMENT: Development
      Serilog__SeqServerUrl: "http://seq:80"
    depends_on:
      - postgres
      - graphhopper
      - seq 

  postgres:
    image: postgis/postgis:16-3.4
    container_name: offroad-postgres
    environment:
      POSTGRES_DB: offroad
      POSTGRES_USER: offroad
      POSTGRES_PASSWORD: offroad
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  graphhopper:
    image: israelhikingmap/graphhopper
    container_name: offroad-graphhopper
    ports:
      - "8989:8989"
    volumes:
      - ../routing/graphhopper/data:/data
      - ../routing/graphhopper/graphhopper-config:/graphhopper-config
    command: --config /graphhopper-config/config.yml
    environment:
      JAVA_OPTS: "-Xmx2g"

  seq:
    image: datalust/seq:latest
    container_name: offroad-seq
    environment:
      - ACCEPT_EULA=Y
      - SEQ_FIRSTRUN_NOAUTHENTICATION=true
    ports:
      - "5341:80" 
    volumes:
      - seqdata:/data
volumes:
  pgdata:
  seqdata: 