// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using NetTopologySuite.Geometries;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using Routing.Infrastructure.Data;

#nullable disable

namespace Routing.Infrastructure.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260729175428_RedefineHeatmapAsDensityGrid")]
    partial class RedefineHeatmapAsDensityGrid
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("public")
                .HasAnnotation("ProductVersion", "8.0.28")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.HasPostgresExtension(modelBuilder, "postgis");
            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Routing.Infrastructure.Persistence.Entities.EdgeEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("edge_id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<double>("ElevationGainMeters")
                        .HasColumnType("double precision")
                        .HasColumnName("elevation_gain");

                    b.Property<LineString>("Geom")
                        .IsRequired()
                        .HasColumnType("geometry(LineString, 4326)")
                        .HasColumnName("geom");

                    b.Property<bool>("HasBarrier")
                        .HasColumnType("boolean")
                        .HasColumnName("has_barrier");

                    b.Property<bool>("HasNoEntry")
                        .HasColumnType("boolean")
                        .HasColumnName("has_no_entry");

                    b.Property<bool>("IsOffroad")
                        .HasColumnType("boolean")
                        .HasColumnName("is_offroad");

                    b.Property<bool>("IsRestricted")
                        .HasColumnType("boolean")
                        .HasColumnName("is_restricted");

                    b.Property<double>("LengthMeters")
                        .HasColumnType("double precision")
                        .HasColumnName("length_m");

                    b.Property<long>("SourceNodeId")
                        .HasColumnType("bigint")
                        .HasColumnName("source_node");

                    b.Property<long>("TargetNodeId")
                        .HasColumnType("bigint")
                        .HasColumnName("target_node");

                    b.HasKey("Id");

                    b.HasIndex("Geom")
                        .HasDatabaseName("idx_gis_edges_geom");

                    NpgsqlIndexBuilderExtensions.HasMethod(b.HasIndex("Geom"), "gist");

                    b.HasIndex("SourceNodeId")
                        .HasDatabaseName("idx_gis_edges_source_node");

                    b.HasIndex("TargetNodeId")
                        .HasDatabaseName("idx_gis_edges_target_node");

                    b.ToTable("edges", "gis");
                });

            modelBuilder.Entity("Routing.Infrastructure.Persistence.Entities.GeometricZoneEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("zone_id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<double?>("AreaSqm")
                        .HasColumnType("double precision")
                        .HasColumnName("area_sqm");

                    b.Property<MultiPolygon>("Geometry")
                        .IsRequired()
                        .HasColumnType("geometry(MultiPolygon, 4326)")
                        .HasColumnName("geom");

                    b.Property<int>("ZoneType")
                        .HasColumnType("integer")
                        .HasColumnName("zone_type");

                    b.HasKey("Id");

                    b.HasIndex("Geometry")
                        .HasDatabaseName("idx_gis_zones_geom");

                    NpgsqlIndexBuilderExtensions.HasMethod(b.HasIndex("Geometry"), "gist");

                    b.ToTable("geometric_zones", "gis");
                });

            modelBuilder.Entity("Routing.Infrastructure.Persistence.Entities.NodeEntity", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("node_id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<double?>("Altitude")
                        .HasColumnType("double precision")
                        .HasColumnName("altitude");

                    b.Property<Point>("Geom")
                        .IsRequired()
                        .HasColumnType("geometry(Point, 4326)")
                        .HasColumnName("geom");

                    b.Property<bool>("IsEntryPoint")
                        .HasColumnType("boolean")
                        .HasColumnName("is_entry_point");

                    b.HasKey("Id");

                    b.HasIndex("Geom")
                        .HasDatabaseName("idx_gis_nodes_geom");

                    NpgsqlIndexBuilderExtensions.HasMethod(b.HasIndex("Geom"), "gist");

                    b.ToTable("nodes", "gis");
                });
#pragma warning restore 612, 618
        }
    }
}
