graphhopper:
  datareader.file: /data/czech-republic-latest.osm.pbf
  graph.location: /data/default-gh
  custom_models.directory: /custom_models
  custom_areas.directory: /data/restricted_areas

  profiles:
    - name: car
      custom_model_files: [car.json]
    - name: offroad_hardcore
      custom_model_files: [car.json, offroad_hardcore.json]
    - name: offroad_balanced
      custom_model_files: [car.json, offroad_balanced.json]
    - name: offroad_shortest
      custom_model_files: [car.json, offroad_shortest.json]
  profiles_ch: []

  profiles_lm: 
    - profile: car
    - profile: offroad_hardcore
    - profile: offroad_balanced
    - profile: offroad_shortest

  graph.encoded_values: car_access, car_average_speed, road_access, surface, track_type, road_class
  custom_models.enabled: true
  track_custom_encoded_values: [barrier]

  vehicles:
    car:
      block_barriers: false

  graph.elevation.provider: srtm
  graph.elevation.cache_dir: /data/srtm

  prepare.min_network_size: 200
  prepare.subnetworks.threads: 1

  routing.snap_preventions_default: tunnel, bridge, ferry
  routing.non_ch.max_waypoint_distance: 1000000

  import.osm.ignored_highways: footway,construction,cycleway,steps,path
  graph.dataaccess.default_type: RAM_STORE

server:
  application_connectors:
    - type: http
      port: 8989
      max_request_header_size: 50k
  request_log:
    appenders: []
  admin_connectors:
    - type: http
      port: 8990

logging:
  appenders:
    - type: console
      time_zone: UTC
      log_format: "%d{yyyy-MM-dd HH:mm:ss.SSS} [%thread] %-5level %logger{36} - %msg%n"
